### ISSUE TITLE
Model and paper

### ISSUE THREAD

**Issue by kbrajwani** [shreeshiv/AIESI#1]
Hey i am reading your paper and it's good.
i have some questions please answer it as you get time
1. In this repo you are using tesseract for box and ocr but i think in original paper you are using something else right?
2. Can you tell me how to finetune the end to end process.

**Comment by shreeshiv** [comment]
Hi Kumar Rajwani,

Thanks for reaching out so far. Glad that you like my paper.
1. Yes, you correctly point out I'm using tesseract for identifying
bounding box and OCR and its original paper I'm using something else. For
paper purposes, I am using data-points with the bounding box and text
within. Now I'm classifying each bounding box. There are lots of options
for finding bounding boxes and OCR. Google vision API, AWS textract and
many others. I would encourage you to explore more about this.
2. If you are using for any real-time problems, I would encourage to go to
SROIE competition, You might find many better solution than my approach on
paper.

Best regards,
shreeshiv.

**Comment by kbrajwani** [comment]
Thanks i will do more research.
